[phases.setup]
nixPkgs = ["ffmpeg", "chromium", "nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []

[start]
cmd = "node index.js"
# force redeploy Thu Apr  2 22:08:54 WAT 2026
